[package]
name = "investigator_analyst"
version = "0.0.0"
edition.workspace = true
authors.workspace = true

[dependencies]

[lib]
name = "analyst"
path = "src/lib.rs"

[[bin]]
name = "analyst"
path = "src/bin/cli.rs"